use std::str::FromStr;
use crate::untyped_ast::*;

grammar;

pub Term: i32 = {
    <n:Num> => n,
    "(" <t:Term> ")" => t,
};

Num: i32 = <s:r"[0-9]+"> => i32::from_str(s).unwrap();

pub Item: Item = {
    <func:Function> => Item::Function(func)
}

Function: Function = {
    <loc_start:@L> "fn" <name:Ident> "{" "}" <loc_end:@L> => {
        Function { loc: Location::new(loc_start, loc_end), name }
    }
}

Ident: String = <s:r"[a-z]+"> => s.to_string();